POST http://localhost:3000/api/users
content-type: application/json

{
    "name": "Bezerra",
    "email": "b2@teste.com",
    "password": "luiz124"
}

###
POST http://localhost:3000/api/login
content-type: application/json

{
    
    "email": "b2@teste.com",
    "password": "luiz124"
}

###

GET http://localhost:3000/api/users


